rvm: '2.2.1'
install:
  -- pip install coveralls
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - bundle exec bin/rake db:create
  - bundle exec bin/rake db:migrate
  - bundle exec rspec spec
  - coverage run --Movie-Snaps setup.py test
after_success: coveralls